# Generated by Django 4.0.6 on 2022-08-06 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_predictor', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField()),
                ('email_verified', models.BooleanField(default=False)),
                ('subscribed_products', models.ManyToManyField(related_name='subscribers', to='product_api.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
