# Generated by Django 4.0.6 on 2022-08-06 13:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Please enter a valid 3-letter currency code', regex='[A-Z]{3}')])),
            ],
        ),
        migrations.CreateModel(
            name='FootballPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(0, 'WIN'), (1, 'DRAW'), (2, 'DOUBLE_CHANCE'), (3, '1.5'), (4, '2.5'), (5, 'CORRECT_SCORE')])),
                ('match_day', models.DateTimeField()),
                ('pick', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FootballTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(0, 'FOOTBALL'), (1, 'BASKETBALL'), (2, 'BASEBALL')])),
                ('price', models.IntegerField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_api.currency')),
            ],
        ),
    ]
