# Generated by Django 4.0.6 on 2022-08-06 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_auth_api', '0001_initial'),
        ('product_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_auth_api.useraccount'),
        ),
        migrations.AddField(
            model_name='price',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_api.currency'),
        ),
        migrations.AddField(
            model_name='footballprediction',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='product_api.footballteam'),
        ),
        migrations.AddField(
            model_name='footballprediction',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='product_api.footballteam'),
        ),
        migrations.AddField(
            model_name='footballprediction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='football_predictions', to='product_api.product'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('type', 'owner')},
        ),
    ]
