# Generated by Django 4.0.6 on 2022-08-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballprediction',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
