# Generated by Django 4.0.6 on 2022-12-05 10:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Please enter a valid 3-letter currency code', regex='[A-Z]{3}')])),
            ],
        ),
        migrations.CreateModel(
            name='SportsTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.PositiveIntegerField(choices=[(0, 'FOOTBALL'), (1, 'BASKETBALL'), (2, 'BASEBALL')])),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('prediction', models.CharField(max_length=50)),
                ('match_day', models.DateTimeField()),
                ('success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tipster', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=50, null=True)),
                ('phone_number', models.IntegerField(null=True, unique=True)),
                ('price', models.IntegerField()),
                ('email_verified', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
                ('subscribers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_account', to='core.useraccount')),
                ('tips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips_owner', to='core.sportstips')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sportstips',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.useraccount'),
        ),
        migrations.AlterUniqueTogether(
            name='sportstips',
            unique_together={('sport', 'owner')},
        ),
    ]
