# Generated by Django 4.1 on 2023-02-23 18:55

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='display_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(default='', max_length=22, unique=True),
        ),
    ]
