# Generated by Django 4.0.6 on 2022-12-05 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_useraccount_ip_address_alter_useraccount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.currency'),
        ),
    ]
