# Generated by Django 4.1 on 2023-02-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_useraccount_bio_alter_useraccount_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
