# Generated by Django 4.0.6 on 2022-12-05 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_useraccount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='subscribers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_account', to='core.useraccount'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='tips',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tips_owner', to='core.sportstips'),
        ),
    ]
