# Generated by Django 4.1 on 2023-02-25 13:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_useraccount_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='free_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='premium_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
    ]
