# Generated by Django 4.0.6 on 2022-12-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_useraccount_subscribers_alter_useraccount_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportstips',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
