# Generated by Django 4.1 on 2023-02-25 14:16

import core.models.user
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pricing_free_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='free_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=core.models.user.default_free_features, null=True, size=7),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='premium_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=core.models.user.default_premium_features, null=True, size=7),
        ),
    ]
