# Generated by Django 4.0.6 on 2022-12-06 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_match_day_sportstips_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='subscribers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipsters', to='core.useraccount'),
        ),
    ]
