# Generated by Django 4.1 on 2023-02-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_wallet_account_number_alter_wallet_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='date',
            new_name='last_update',
        ),
    ]
