# Generated by Django 4.0.6 on 2022-12-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_useraccount_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='subscribers',
            field=models.ManyToManyField(related_name='tipsters', to='core.useraccount'),
        ),
    ]
