# Generated by Django 4.0.6 on 2022-12-07 14:50

import core.shared.model_utils
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_useraccount_subscribers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(0, 'FREE'), (1, 'TRIAL'), (2, 'PREMIUM')])),
                ('code', models.CharField(default=core.shared.model_utils.generate_unique_code, max_length=32)),
                ('price', models.IntegerField(default=0)),
                ('period', models.IntegerField(default=0)),
                ('date_initialized', models.DateTimeField(auto_now=True)),
                ('date_expired', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('prediction', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('success', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='core.game')),
            ],
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='price',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='tips',
        ),
        migrations.AddField(
            model_name='currency',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='SportsTips',
        ),
        migrations.AddField(
            model_name='tips',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.useraccount'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.currency'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipster_subscriptions', to='core.useraccount'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bettor_subscriptions', to='core.useraccount'),
        ),
        migrations.AddField(
            model_name='price',
            name='issuer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.useraccount'),
        ),
        migrations.AlterUniqueTogether(
            name='tips',
            unique_together={('game', 'issuer', 'home_team', 'away_team', 'date')},
        ),
    ]
