# Generated by Django 4.1 on 2023-02-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_date_pricing_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='account_number',
            new_name='bank_account_number',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='bank',
            new_name='bank_name',
        ),
    ]
