# Generated by Django 4.1 on 2023-02-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_account_number_wallet_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bank_account_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bank_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
