# Generated by Django 4.0.6 on 2022-12-07 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_game_price_subscription_tips_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.IntegerField(default=0)),
                ('payment_price', models.IntegerField(default=0)),
                ('exchange_rate', models.IntegerField(null=True)),
                ('base_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_currency_payment', to='core.currency')),
                ('payment_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_currency_payment', to='core.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('period', models.PositiveIntegerField(choices=[(0, 'MONTHLY'), (1, 'QUARTERLY'), (2, 'YEARLY')])),
                ('percentage_discount', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='period',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_subscription', to='core.payment'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pricing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pricing'),
        ),
    ]
