# Generated by Django 4.0.6 on 2022-12-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_payment_pricing_remove_subscription_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_expired',
            field=models.DateTimeField(null=True),
        ),
    ]
