# Generated by Django 4.1 on 2023-02-28 14:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_wallet_bank_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='league',
            new_name='competition',
        ),
        migrations.RenameField(
            model_name='sportsevent',
            old_name='league',
            new_name='competition',
        ),
        migrations.AddField(
            model_name='sportsevent',
            name='added_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.useraccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsevent',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
