# Generated by Django 4.1 on 2023-02-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_league_play_competition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p2psportsbet',
            old_name='stake_per_bettor',
            new_name='stake',
        ),
    ]
