# Generated by Django 4.0.6 on 2022-12-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_subscription_date_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='period',
            field=models.IntegerField(default=-1),
        ),
    ]
