# Generated by Django 4.1 on 2023-02-28 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_stake_per_bettor_p2psportsbet_stake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsevent',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.useraccount'),
        ),
    ]
