# Generated by Django 4.0.6 on 2022-12-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_subscription_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='trial_period',
            field=models.PositiveIntegerField(default=14),
        ),
    ]
