# Generated by Django 4.0.6 on 2022-12-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pricing_trial_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='period',
        ),
    ]
