# Generated by Django 4.1 on 2023-02-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_sportsevent_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2psportsbet',
            name='matched_time',
            field=models.DateTimeField(null=True),
        ),
    ]
