# Generated by Django 4.1 on 2023-02-28 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_p2psportsbet_matched_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2psportsbet',
            name='backer_option',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='p2psportsbet',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.currency'),
        ),
    ]
