# Generated by Django 4.1 on 2023-03-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_p2psportsbet_backer_option_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='game',
            new_name='sports',
        ),
    ]
