# Generated by Django 4.0.6 on 2022-12-14 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_subscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipster_subscriptions', to='core.useraccount'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bettor_subscriptions', to='core.useraccount'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tips', to='core.game'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='pricing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pricing'),
        ),
    ]
