# Generated by Django 4.0.6 on 2022-12-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_useraccount_bio_alter_subscription_issuer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(max_length=22, null=True, unique=True),
        ),
    ]
