# Generated by Django 4.1 on 2023-03-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_game_play_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2psportsbetinvitation',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
