# Generated by Django 4.0.6 on 2022-12-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_useraccount_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('bank_code', models.IntegerField()),
                ('account_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='display_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
