# Generated by Django 4.1 on 2023-03-02 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_p2psportsbetinvitation_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2psportsbetinvitation',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='core.p2psportsbet'),
        ),
    ]
