# Generated by Django 4.1 on 2023-03-03 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_p2psportsbetinvitation_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2psportsbet',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.transaction'),
        ),
    ]
