# Generated by Django 4.0.6 on 2022-12-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_wallet_useraccount_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='bank_code',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bank',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
