# Generated by Django 4.1 on 2023-03-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_p2psportsbet_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='P2PSportsBetInvitation',
            new_name='P2PSportsBetChallenge',
        ),
    ]
