# Generated by Django 4.1 on 2023-03-04 20:10

import core.shared.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_p2psportsbetinvitation_p2psportsbetchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PSportsWager',
            fields=[
                ('id', models.CharField(default=core.shared.model_utils.generate_wager_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('market', models.CharField(max_length=50)),
                ('placed_time', models.DateTimeField(auto_now_add=True)),
                ('matched_time', models.DateTimeField(null=True)),
                ('backer_option', models.BooleanField()),
                ('layer_option', models.BooleanField(null=True)),
                ('stake', models.FloatField()),
                ('matched', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'VOID'), (1, 'SETTLED'), (2, 'PENDING')], default=2)),
                ('backer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backer_wager', to='core.useraccount')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sportsevent')),
                ('layer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_wager', to='core.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='P2PSportsWagerChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_initialized', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('requestee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestee_request', to='core.useraccount')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestor_request', to='core.useraccount')),
                ('wager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='core.p2psportswager')),
            ],
        ),
        migrations.RemoveField(
            model_name='p2psportsbetchallenge',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='p2psportsbetchallenge',
            name='requestee',
        ),
        migrations.RemoveField(
            model_name='p2psportsbetchallenge',
            name='requestor',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'DEPOSIT'), (1, 'WITHDRAWAL'), (2, 'WAGER')], editable=False),
        ),
        migrations.DeleteModel(
            name='P2PSportsBet',
        ),
        migrations.DeleteModel(
            name='P2PSportsBetChallenge',
        ),
        migrations.AddField(
            model_name='p2psportswager',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.transaction'),
        ),
        migrations.AddField(
            model_name='p2psportswager',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.useraccount'),
        ),
    ]
