# Generated by Django 4.0.6 on 2022-12-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_game_id_alter_game_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tips',
            name='published',
        ),
        migrations.AddField(
            model_name='tips',
            name='league',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
