# Generated by Django 4.1 on 2023-03-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_p2psportswager_p2psportswagerchallenge_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='P2PSportsWager',
            new_name='SportsWager',
        ),
        migrations.RenameModel(
            old_name='P2PSportsWagerChallenge',
            new_name='SportsWagerChallenge',
        ),
    ]
