# Generated by Django 4.0.6 on 2022-12-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_tips_published_tips_league'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tips',
            unique_together={('issuer', 'home_team', 'away_team', 'date')},
        ),
        migrations.RemoveField(
            model_name='tips',
            name='game',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
