# Generated by Django 4.1 on 2023-03-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_p2psportswager_sportswager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'DEPOSIT'), (1, 'WITHDRAWAL'), (2, 'WAGER'), (3, 'PURCHASE')], editable=False),
        ),
    ]
