# Generated by Django 4.1 on 2023-03-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='currency',
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
    ]
