# Generated by Django 4.1 on 2023-03-07 21:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_useraccount_currency_wallet_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='authorizations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=5),
        ),
    ]
