# Generated by Django 4.0.6 on 2022-12-28 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_tips_unique_together_tips_game_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tips',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tips',
            name='game',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='tips', to='core.game'),
            preserve_default=False,
        ),
    ]
