# Generated by Django 4.1 on 2023-03-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_wallet_authorizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='receipent_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
