# Generated by Django 4.0.6 on 2022-12-29 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_tips_success_tips_result_tips_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tips',
            old_name='date',
            new_name='match_day',
        ),
        migrations.AddField(
            model_name='tips',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
