# Generated by Django 4.0.6 on 2022-12-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_date_tips_match_day_tips_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='game',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
