# Generated by Django 4.0.6 on 2022-12-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_tips_game_delete_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='date_expired',
            new_name='expiration_date',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='date_initialized',
            new_name='subscription_date',
        ),
    ]
