# Generated by Django 4.1 on 2023-03-09 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_sports_sportsgame_remove_sportswager_event_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sports',
            new_name='Sport',
        ),
        migrations.RemoveField(
            model_name='sportswager',
            name='currency',
        ),
        migrations.AlterField(
            model_name='sportswager',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.sportsgame'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sportswager',
            name='transaction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.transaction'),
            preserve_default=False,
        ),
    ]
