# Generated by Django 4.0.6 on 2023-01-01 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_date_expired_subscription_expiration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCodeTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('bookie', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_free', models.BooleanField(default=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='MatchTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=15)),
                ('league', models.CharField(max_length=20)),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('prediction', models.CharField(max_length=50)),
                ('match_day', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=10, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'LOSS'), (1, 'WIN'), (2, 'PENDING')], default=2)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.useraccount')),
            ],
        ),
        migrations.DeleteModel(
            name='Tips',
        ),
    ]
