# Generated by Django 4.0.6 on 2023-02-07 22:37

import core.shared.model_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_bookingcodetips_matchtips_delete_tips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='base_currency',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='base_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_price',
        ),
        migrations.AddField(
            model_name='payment',
            name='period',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='code',
            field=models.CharField(default=core.shared.model_utils.generate_unique_code, editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_owner', to='core.wallet'),
        ),
    ]
