# Generated by Django 4.0.6 on 2023-02-08 18:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_base_currency_payment_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='trial_period',
        ),
        migrations.AddField(
            model_name='pricing',
            name='free_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='premium_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_payment', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'FREE'), (1, 'PREMIUM')]),
        ),
    ]
