# Generated by Django 4.1 on 2023-03-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_sportsgame_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportsgame',
            old_name='is_played',
            new_name='is_wager_played',
        ),
        migrations.AlterField(
            model_name='sportswager',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wagers', to='core.sportsgame'),
        ),
    ]
