# Generated by Django 4.1 on 2023-03-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_competition_teams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
