# Generated by Django 4.0.6 on 2023-02-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_matchtips_game_alter_matchtips_league'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchTips',
            new_name='Play',
        ),
        migrations.DeleteModel(
            name='BookingCodeTips',
        ),
    ]
