# Generated by Django 4.1 on 2023-03-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_teams_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='country',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
