# Generated by Django 4.0.6 on 2023-02-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_transaction_rename_is_free_play_is_premium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_tipster',
        ),
    ]
