# Generated by Django 4.1 on 2023-03-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_competition_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='country',
        ),
    ]
