# Generated by Django 4.0.6 on 2023-02-20 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_useraccount_is_tipster'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('home', models.CharField(max_length=100)),
                ('away', models.CharField(max_length=100)),
                ('match_day', models.DateTimeField()),
                ('result', models.CharField(max_length=10, null=True)),
            ],
            options={
                'unique_together': {('game', 'league', 'home', 'away', 'match_day')},
            },
        ),
        migrations.CreateModel(
            name='P2PBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=50)),
                ('date_initialized', models.DateTimeField(auto_now_add=True)),
                ('issuer_option', models.BooleanField(null=True)),
                ('player_option', models.BooleanField(null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'VOID'), (1, 'SETTLED'), (2, 'PENDING')], default=2)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sportsevent')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuer_bet', to='core.useraccount')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_bet', to='core.useraccount')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.useraccount')),
            ],
        ),
    ]
