# Generated by Django 4.1 on 2023-03-10 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.sport'),
            preserve_default=False,
        ),
    ]
