# Generated by Django 4.0.6 on 2023-02-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_sportsevent_p2pbet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sportsevent',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='P2PBetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_initialized', models.DateTimeField(auto_now_add=True)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.p2pbet')),
                ('requestee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestee_request', to='core.useraccount')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestor_request', to='core.useraccount')),
            ],
        ),
    ]
