# Generated by Django 4.1 on 2023-03-10 11:06

import core.shared.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_market_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportswager',
            name='id',
            field=models.CharField(default=core.shared.model_utils.generate_wager_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
