# Generated by Django 4.0.6 on 2023-02-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_sportsevent_unique_together_p2pbetrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='P2PBetRequest',
            new_name='P2PBetInvitation',
        ),
    ]
