# Generated by Django 4.0.6 on 2023-02-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_rename_p2pbetrequest_p2pbetinvitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='issuer',
            new_name='payment_issuer',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='reference',
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'FAILED'), (1, 'SUCCEED'), (2, 'PENDING')], default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(default='USD', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='currency_transaction', to='core.currency'),
            preserve_default=False,
        ),
    ]
