# Generated by Django 4.1 on 2023-03-10 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_sportswager_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='play',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='play',
            name='issuer',
        ),
        migrations.CreateModel(
            name='PlaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.useraccount')),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='slip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.playslip'),
            preserve_default=False,
        ),
    ]
