# Generated by Django 4.0.6 on 2023-02-21 17:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_issuer_transaction_payment_issuer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p2pbet',
            old_name='issuer',
            new_name='backer',
        ),
        migrations.RenameField(
            model_name='p2pbet',
            old_name='issuer_option',
            new_name='backer_option',
        ),
        migrations.RenameField(
            model_name='p2pbet',
            old_name='player',
            new_name='layer',
        ),
        migrations.RenameField(
            model_name='p2pbet',
            old_name='player_option',
            new_name='layer_option',
        ),
        migrations.RenameField(
            model_name='p2pbet',
            old_name='date_initialized',
            new_name='placed_time',
        ),
        migrations.AddField(
            model_name='p2pbet',
            name='currency',
            field=models.ForeignKey(default='USD', on_delete=django.db.models.deletion.CASCADE, to='core.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='p2pbet',
            name='matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='p2pbet',
            name='matched_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='p2pbet',
            name='stake_per_bettor',
            field=models.FloatField(default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='withheld',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_issuer',
            field=models.PositiveIntegerField(choices=[(0, 'PAYSTACK')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'DEPOSIT'), (1, 'WITHDRAWAL'), (2, 'BET')], editable=False),
        ),
    ]
