# Generated by Django 4.1 on 2023-03-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_play_date_added_remove_play_is_premium_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playslip',
            old_name='name',
            new_name='title',
        ),
    ]
