# Generated by Django 4.1 on 2023-03-12 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_rename_name_playslip_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='email_verified',
        ),
    ]
