# Generated by Django 4.1 on 2023-03-13 10:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_useraccount_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2),
        ),
    ]
