# Generated by Django 4.1 on 2023-03-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_useraccount_facebook_handle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='facebook_handle',
            field=models.CharField(blank=True, default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='instagram_handle',
            field=models.CharField(blank=True, default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='twitter_handle',
            field=models.CharField(blank=True, default='', max_length=22),
        ),
    ]
