# Generated by Django 4.1 on 2023-03-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_feedback_privacypolicy_termsofuse_waitlist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='text',
            new_name='message',
        ),
    ]
