# Generated by Django 4.1 on 2023-03-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_rename_text_feedback_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='receipent_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
