# Generated by Django 4.1 on 2023-03-19 00:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_wallet_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='authorizations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=5),
        ),
    ]
