# Generated by Django 4.1 on 2023-03-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_wallet_authorizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
