# Generated by Django 4.1 on 2023-03-20 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_useraccount_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(default='NGN', on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
            preserve_default=False,
        ),
    ]
