# Generated by Django 4.1 on 2023-03-22 14:25

import core.models.user
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_wallet_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='country',
            field=django_countries.fields.CountryField(default='NG', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='free_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=core.models.user.default_free_features, size=7),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='premium_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=core.models.user.default_premium_features, size=7),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='pricing',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='core.pricing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='wallet',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_owner', to='core.wallet'),
            preserve_default=False,
        ),
    ]
