# Generated by Django 4.1 on 2023-03-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_useraccount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playslip',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
