# Generated by Django 4.1 on 2023-06-04 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_useraccount_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.CharField(max_length=20)),
                ('competition', models.CharField(max_length=50)),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('match_day', models.DateTimeField()),
                ('result', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='play',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='play',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='play',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='play',
            name='match_day',
        ),
        migrations.RemoveField(
            model_name='play',
            name='result',
        ),
        migrations.RemoveField(
            model_name='play',
            name='sports',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='wallet',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='play',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.match'),
        ),
    ]
