# Generated by Django 4.1 on 2023-06-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_match_remove_play_away_team_remove_play_competition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='meta',
            field=models.JSONField(null=True),
        ),
    ]
