# Generated by Django 4.1 on 2023-06-05 11:56

import core.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_wallet_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='meta',
            field=models.JSONField(default=core.models.user.meta_default),
        ),
    ]
