# Generated by Django 4.1 on 2023-06-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_pricing_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_issuer',
        ),
    ]
