# Generated by Django 4.0.6 on 2022-08-02 15:54

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_predictor', models.BooleanField(default=False)),
                ('country', django_countries.fields.CountryField(blank='(Select Country)', max_length=2)),
                ('mobile_no', models.IntegerField()),
                ('email_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
